use cron_tab::*;
use chrono::Utc;
use crate::{Job, JobParams};
use std::process::Command;
use std::fs;
use std::path::PathBuf;
use std::error::Error;

//let utc_tz = Utc;


pub fn create_job(job: Job, cron: &mut Cron<Utc>) {
    cron.add_fn(&job.timing.full_timing(), move || execute_job(&job.params).unwrap()).unwrap();
}

//TODO Add global log to capture errors not generated by user commands
//TODO Find a way to redirect errors
//TODO Append to output (optional?)
fn execute_job(params: &JobParams) -> core::result::Result<(), Box<dyn Error>> {
    debug!("The command is: {}", params.full_command());
    let output = Command::new("sh")
                                .arg("-c")
                                .arg(&params.command)
                                .output()
                                .map_err(|e| {
                                    error!("Error when running command: {:?}", e);
                                    e
                                })?;
    fs::write(&params.log_location, output.stdout).map_err(|e| {
        error!("Could not write to log location: {:?}", e);
        e
    })?;
    let mut error_path = PathBuf::from(&params.log_location);
    error_path.pop();
    error_path.push("error.log");
    debug!("error path: {:?}", error_path);
    fs::write(error_path, output.stderr).map_err(|e| {
        error!("Could not write to error location: {:?}", e);
        e
    })?;
    Ok(())
}